Models/ErrorViewModel.cs
using System;

namespace TalkToTalk.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TalkToTalk.Models
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Логин")]
        public string UserName { get; set; }

        [Required]
        [Display(Name = "Пароль")]
        public string Password { get; set; }


        [Display(Name = "Запомнить меня?")]
        public bool RememberMe { get; set; }
    }
}

Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TalkToTalk.Domain;

namespace TalkToTalk.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private readonly DataManager dataManager;

        public HomeController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

        public IActionResult Index()
        {
            return View(dataManager.NewsItems.GetNewsItems());
        }
    }
}

Areas/Admin/Controllers/NewsItemsController.cs
using System;
using System.IO;
using System.Linq;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TalkToTalk.Domain;
using TalkToTalk.Domain.Entities;

namespace TalkToTalk.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class NewsItemsController : Controller
    {
        private readonly DataManager dataManager;
        private readonly IWebHostEnvironment hostingEnvironment;
        private readonly UserManager<IdentityUser> userManager;
        public NewsItemsController(DataManager dataManager, UserManager<IdentityUser> userManager,IWebHostEnvironment hostingEnvironment)
        {
            this.dataManager = dataManager;
            this.hostingEnvironment = hostingEnvironment;
            this.userManager = userManager;
        }

        public IActionResult Edit(Guid id)
        {
            var entity = id == default ? new NewsItem() : dataManager.NewsItems.GetNewsItemById(id);
            return View(entity);
        }
        [HttpPost]
        public IActionResult Edit(NewsItem model, IFormFile titleImageFile)
        {
            if (ModelState.IsValid)
            {
                if (titleImageFile != null)
                {
                    model.TitleImagePath = titleImageFile.FileName;
                    using (var stream = new FileStream(Path.Combine(hostingEnvironment.WebRootPath, "images/", titleImageFile.FileName), FileMode.Create))
                    {
                        titleImageFile.CopyTo(stream);
                    }
                }
                model.AuthorId = userManager.Users.FirstOrDefault(x=> x.UserName == User.Identity.Name).Id;
                dataManager.NewsItems.SaveNewsItem(model);
                return RedirectToAction(nameof(HomeController.Index), "Home");
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            dataManager.NewsItems.DeleteNewsItem(id);
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }
    }
}

Controllers/AccountController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TalkToTalk.Models;
using SignInResult = Microsoft.AspNetCore.Identity.SignInResult;

namespace TalkToTalk.Controllers
{
    public class AccountController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;

        public AccountController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        [AllowAnonymous]
        public IActionResult Login(string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginViewModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                IdentityUser user = await userManager.FindByNameAsync(model.UserName);
                if (user != null)
                {
                    await signInManager.SignOutAsync();
                    SignInResult result =
                        await signInManager.PasswordSignInAsync(user, model.Password, model.RememberMe, false);
                    if (result.Succeeded)
                        return Redirect(returnUrl ?? "/");
                }
                ModelState.AddModelError(nameof(LoginViewModel.UserName), "Неверный логин или пароль");
            }
            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TalkToTalk.Domain;
using TalkToTalk.Domain.Entities;
using TalkToTalk.Models;

namespace TalkToTalk.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly DataManager _dataManager;

        public HomeController(ILogger<HomeController> logger, DataManager dataManager)
        {
            _logger = logger;
            _dataManager = dataManager;
        }

        public IActionResult Index()
        {
            return View(_dataManager);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using TalkToTalk.Domain;
using TalkToTalk.Domain.Entities;

namespace TalkToTalk.Controllers
{
    public class PostController : Controller
    {
        private readonly DataManager dataManager;

        public PostController(DataManager dataManager)
        {
            this.dataManager = dataManager;
        }

     
        public IActionResult Index(Guid id)
        {
            var entity = id == default ? new NewsItem() : dataManager.NewsItems.GetNewsItemById(id);
            entity.Author = dataManager.UserRepository.GetUserById(entity.AuthorId);
            return View(entity);
        }


        //TODO unique likes per user
        public IActionResult Like(Guid id)
        {
            var entity = id == default ? new NewsItem() : dataManager.NewsItems.GetNewsItemById(id);
            entity.Likes++;
            dataManager.NewsItems.SaveNewsItem(entity);
            return RedirectToAction("Index", "Post", new {id = id});
        }
    }
}

Areas/Admin/Views/Home/Index.cshtml
@model IQueryable<NewsItem>
@{
    string strTitle = "Панель администратора";
    ViewBag.Title = strTitle;
}

<div>
    <h3>News</h3>
    <div class="div-box">
        <a asp-area="Admin" asp-controller="NewsItems" asp-action="Edit" asp-route-id="">Add post</a>
    </div>
    @if (Model.Any())
    {
        <div>
            @foreach (NewsItem entity in Model)
            {
                <div>
                    <a asp-area="Admin" asp-controller="NewsItems" asp-action="Edit" asp-route-id="@entity.Id">Modify</a>
                    
                    <form style="display: inline-block;" id="form-@entity.Id" asp-area="Admin" asp-controller="NewsItems" asp-action="Delete" method="post">
                        <input type="hidden" name="id" value="@entity.Id"/>
                        <a href="#" onclick="document.getElementById('form-@entity.Id').submit();">Remove</a>
                    </form>
                    
                    <a asp-area="" asp-controller="Post" asp-action="Index" asp-route-id="@entity.Id">
                        @($"{entity.Title}")
                    </a>
                </div>
            }
        </div>
    }
</div>

<div class="div-box">
    <form asp-area="" asp-controller="Account" asp-action="Logout" method="post">
        <input type="submit" value="Logout"/>
    </form>
</div>

Areas/Admin/Views/NewsItems/Edit.cshtml
@model NewsItem
@{
    string strTitle = "Modify post";
    ViewBag.Title = strTitle;
}

<script src="~/js/ckeditor/ckeditor.js"></script>

<div>
    <h2>@strTitle</h2>
    <div>
        <form asp-area="Admin" asp-controller="NewsItems" asp-action="Edit" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdded" />
            <input type="hidden" asp-for="TitleImagePath" />

            <div asp-validation-summary="All"></div>
            <div class="div-box">
                <label asp-for="Title"></label>
                <input asp-for="Title" />
                <span asp-validation-for="Title"></span>
            </div>
            <div class="div-box">
                <label asp-for="Subtitle"></label>
                <input asp-for="Subtitle" />
                <span asp-validation-for="Subtitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="Text"></label>
                <textarea asp-for="Text"></textarea>
                <span asp-validation-for="Text"></span>
            </div>
            <div class="div-box">
                <label asp-for="TitleImagePath"></label>
                <input type="file" name="titleImageFile" id="titleImageFile" />
                <div>
                    <img class="img-block" src="~/images/@Model.TitleImagePath" />
                </div>
            </div>
            <div class="div-box">
                <label asp-for="MetaTitle"></label>
                <input asp-for="MetaTitle" />
                <span asp-validation-for="MetaTitle"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaDescription"></label>
                <input asp-for="MetaDescription" />
                <span asp-validation-for="MetaDescription"></span>
            </div>
            <div class="div-box">
                <label asp-for="MetaKeywords"></label>
                <input asp-for="MetaKeywords" />
                <span asp-validation-for="MetaKeywords"></span>
            </div>
            <input type="submit" value="Сохранить" />
        </form>
    </div>
</div>



<script>
    window.onload = function() {
        var newCKEdit = CKEDITOR.replace('@Html.IdFor(x=>x.Text)');
        newCKEdit.updateElement();
    }
</script>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model DataManager

<div id="wrapper">

    <!-- Header -->
    @await Html.PartialAsync("HeaderPartial")

    <!-- Menu -->
    @await Html.PartialAsync("HeaderMenuPartial")

<!-- Main -->
    <div id="main">
        
        @foreach (NewsItem item in Model.NewsItems.GetNewsItems())
        {
            item.Author = Model.UserRepository.GetUserById(item.AuthorId);
            @await Html.PartialAsync("PostsPartial", item)
        }

        <!-- Pagination -->
        <ul class="actions pagination">
            <li><a href="" class="button-white large previous">Previous Page</a></li>
            <li><a href="#" class="button-white large next">Next Page</a></li>
        </ul>
    </div>

    <!-- Sidebar -->
    @await Html.PartialAsync("SidebarPartial", Model)

</div>

Views/Post/Index.cshtml
@model NewsItem

		<!-- Wrapper -->
			<div id="wrapper" style="display: block">
                <!-- Header -->
					@await Html.PartialAsync("HeaderPartial")
                <!-- Main -->
					<div id="main">
                        <!-- Post -->
							<article class="post">
								<header>
									<div class="title">
										<h2><a asp-controller="Post" asp-action="Index" asp-route-id="@Model.Id">@Model.Title</a></h2>
										<p>@Model.MetaKeywords</p>
									</div>
									<div class="meta">
										<time class="published" datetime="2015-11-01">@Model.DateAdded.ToLongDateString()</time>
										<a href="#" class="author"><span class="name">@Model.Author.UserName</span><img src="images/avatar.jpg" alt="" /></a>
									</div>
								</header>
                                <span class="image featured"><img src="~/images/@Model.TitleImagePath" alt="" /></span>
								@Html.Raw(Model.Text)
                                <footer>
									<ul class="stats">
                                        <li><a asp-controller="Post" asp-action="Like" asp-route-id="@Model.Id" class="icon solid fa-heart">@Model.Likes</a></li>
                                    </ul>
								</footer>
							</article>

					</div>

				<!-- Footer -->
					<section id="footer" style="text-align: center;">
						<ul class="icons">
							<li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
							<li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
							<li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
							<li><a href="#" class="icon solid fa-rss"><span class="label">RSS</span></a></li>
							<li><a href="#" class="icon solid fa-envelope"><span class="label">Email</span></a></li>
						</ul>
						<p class="copyright">&copy; Untitled. Design: <a href="http://html5up.net">HTML5 UP</a>. Images: <a href="http://unsplash.com">Unsplash</a>.</p>
					</section>

			</div>

Views/Shared/AboutPartial.cshtml
<section class="blurb">
    <h2 class="header-title">About</h2>
    <p>Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl. Sed mattis nunc id lorem euismod amet placerat. Vivamus porttitor magna enim, ac accumsan tortor cursus at phasellus sed ultricies.</p>
    <ul class="actions">
        <li><a href="#" class="button-white">Learn More</a></li>
    </ul>
</section>

Views/Shared/CssPartial.cshtml
<link rel="stylesheet" href="~/css/main.css" asp-append-version="true"/>

Views/Shared/FooterPartial.cshtml
<section id="footer">
    <ul class="icons">
        <li><a href="#" class="icon brands fa-twitter"><span class="label">Twitter</span></a></li>
        <li><a href="#" class="icon brands fa-facebook-f"><span class="label">Facebook</span></a></li>
        <li><a href="#" class="icon brands fa-instagram"><span class="label">Instagram</span></a></li>
        <li><a href="#" class="icon solid fa-rss"><span class="label">RSS</span></a></li>
        <li><a href="#" class="icon solid fa-envelope"><span class="label">Email</span></a></li>
    </ul>
    <p class="copyright">&copy; Untitled. Design: <a href="http://html5up.net">HTML5 UP</a>. Images: <a href="http://unsplash.com">Unsplash</a>.</p>
</section>

Views/Shared/HeaderMenuPartial.cshtml
<section id="menu">

    <!-- Search -->
    <section>
        <form class="search" method="get" action="#">
            <input type="text" name="query" placeholder="Search" />
        </form>
    </section>

    <!-- Links -->
    <section>
        <ul class="links">
            <li>
                <a href="#">
                    <h3>Lorem ipsum</h3>
                    <p>Feugiat tempus veroeros dolor</p>
                </a>
            </li>
            <li>
                <a href="#">
                    <h3>Dolor sit amet</h3>
                    <p>Sed vitae justo condimentum</p>
                </a>
            </li>
            <li>
                <a href="#">
                    <h3>Feugiat veroeros</h3>
                    <p>Phasellus sed ultricies mi congue</p>
                </a>
            </li>
            <li>
                <a href="#">
                    <h3>Etiam sed consequat</h3>
                    <p>Porta lectus amet ultricies</p>
                </a>
            </li>
        </ul>
    </section>

    <!-- Actions -->
    <section>
        <ul class="actions stacked">
            <li><a href="#" class="button large fit">Log In</a></li>
        </ul>
    </section>

</section>

Views/Shared/HeaderPartial.cshtml
@using TalkToTalk.Service
<header id="header">
    <h1><a asp-controller="Home" asp-action="Index">@Config.BlogName</a></h1>
    @*<nav class="links">
        <ul>
            <li><a href="#">Lorem</a></li>
            <li><a href="#">Ipsum</a></li>
            <li><a href="#">Feugiat</a></li>
            <li><a href="#">Tempus</a></li>
            <li><a href="#">Adipiscing</a></li>
        </ul>
    </nav>*@
    <!-- <nav class="main">
        <ul>
            <li class="search">
                <a class="fa-search" href="#search">Search</a>
                <form id="search" method="get" action="#">
                    <input type="text" name="query" placeholder="Search" />
                </form>
            </li>
            <li class="menu">
                <a class="fa-bars" href="#menu">Menu</a>
            </li>
        </ul>
    </nav> -->
</header>

Views/Shared/MetatagsPartial.cshtml
<title>Future Imperfect by HTML5 UP</title>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />

Views/Shared/PostsPartial.cshtml
@model NewsItem

<article class="post">
    <header>
        <div class="title">
            <h2><a asp-controller="Post" asp-action="Index" asp-route-id="@Model.Id">@Model.Title</a></h2>
            <p>@Model.MetaKeywords</p>
        </div>
        <div class="meta">
            <time class="published" datetime="2015-11-01">@Model.DateAdded.ToLongDateString()</time>
            <a href="#" class="author"><span class="name">@Model.Author.UserName</span><img src="images/avatar.jpg" alt="" /></a>
        </div>
    </header>

    <a asp-controller="Post" asp-action="Index" asp-route-id="@Model.Id" class="image featured"><img src="~/images/@Model.TitleImagePath" alt="" /></a> y
    <p>@Model.Subtitle</p>
    <footer>
        <ul class="actions">
            <li><a asp-controller="Post" asp-action="Index" asp-route-id="@Model.Id" class="button large">Продолжить читать</a></li>
        </ul>
        <ul class="stats">
            <li><a class="icon solid fa-heart">@Model.Likes</a></li>
        </ul>
    </footer>
</article>

Views/Shared/ScriptsPartial.cshtml
<script src="~/js/jquery.min.js" asp-append-version="true"></script>
<script src="~/js/browser.min.js" asp-append-version="true"></script>
<script src="~/js/breakpoints.min.js" asp-append-version="true"></script>
<script src="~/js/util.js" asp-append-version="true"></script>
<script src="~/js/main.js" asp-append-version="true"></script>

Views/Shared/SidebarPartial.cshtml
@using TalkToTalk.Service
@model DataManager
<section id="sidebar">

    <!-- Intro -->
    <section id="intro">
        <a asp-controller="Home" asp-action="Index" class="logo"><img src="images/logo.jpg" alt="" /></a>
        <header>
            <h2 class="header-title">@Config.BlogName</h2>
            <p class="header-title">Сюда надо что-то писать...</p>
        </header>
    </section>

    <!-- Mini Posts -->
    <section>
        <div class="mini-posts">
            
            @foreach (NewsItem item in Model.NewsItems.GetTopFiveItems())
            {
                <!-- Mini Post -->
                <article class="mini-post">
                    <header>
                        <h3><a asp-controller="Post" asp-action="Index" asp-route-id="@item.Id">@item.Title</a></h3>
                        <time class="published" datetime="2015-10-20">@item.DateAdded.ToLongDateString()</time>
                        <a href="#" class="author"><img src="images/avatar.jpg" alt=""/></a>
                    </header>
                    <a asp-controller="Post" asp-action="Index" asp-route-id="@item.Id" class="image"><img src="~/images/@item.TitleImagePath" alt=""/></a>
                </article>
            }
        </div>
    </section>

    <!-- Posts List -->
    @*<section>
        <ul class="posts">
            <li>
                <article>
                    <header>
                        <h3 class="mini-post-title"><a href="single.html">Congue ullam corper lorem ipsum dolor</a></h3>
                        <time class="published" datetime="2015-10-06">October 7, 2015</time>
                    </header>
                    <a href="single.html" class="image"><img src="images/pic12.jpg" alt="" /></a>
                </article>
            </li>
        </ul>
    </section>*@

    <!-- About -->
    @await Html.PartialAsync("AboutPartial")

    <!-- Footer -->
    @await Html.PartialAsync("FooterPartial")

</section>

Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    @await Html.PartialAsync("MetatagsPartial")
    @await  Html.PartialAsync("CssPartial")
</head>
<body class="is-preload">

    <!-- Wrapper -->
   @RenderBody()

    <!-- Scripts -->
   @await Html.PartialAsync("ScriptsPartial")

</body>
</html>